name: Terraform Apply 

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify Terraform version
        run: terraform --version
